var annotated_dup =
[
    [ "comma", "namespacecomma.html", [
      [ "Agglomerator", "classcomma_1_1_agglomerator.html", "classcomma_1_1_agglomerator" ],
      [ "Agglomerator_Anisotropic", "classcomma_1_1_agglomerator___anisotropic.html", "classcomma_1_1_agglomerator___anisotropic" ],
      [ "Agglomerator_Biconnected", "classcomma_1_1_agglomerator___biconnected.html", "classcomma_1_1_agglomerator___biconnected" ],
      [ "Agglomerator_Isotropic", "classcomma_1_1_agglomerator___isotropic.html", "classcomma_1_1_agglomerator___isotropic" ],
      [ "Agglomerator_Iterative", "classcomma_1_1_agglomerator___iterative.html", "classcomma_1_1_agglomerator___iterative" ],
      [ "Bimap", "classcomma_1_1_bimap.html", "classcomma_1_1_bimap" ],
      [ "Coarse_Cell", "classcomma_1_1_coarse___cell.html", "classcomma_1_1_coarse___cell" ],
      [ "Coarse_Cell_Container", "classcomma_1_1_coarse___cell___container.html", "classcomma_1_1_coarse___cell___container" ],
      [ "Coarse_Cell_Subgraph", "classcomma_1_1_coarse___cell___subgraph.html", "classcomma_1_1_coarse___cell___subgraph" ],
      [ "CustomPairGreaterFunctor", "structcomma_1_1_custom_pair_greater_functor.html", "structcomma_1_1_custom_pair_greater_functor" ],
      [ "CustomPairLessFunctor", "structcomma_1_1_custom_pair_less_functor.html", "structcomma_1_1_custom_pair_less_functor" ],
      [ "Dual_Graph", "classcomma_1_1_dual___graph.html", "classcomma_1_1_dual___graph" ],
      [ "Graph", "classcomma_1_1_graph.html", "classcomma_1_1_graph" ],
      [ "Neighbourhood", "classcomma_1_1_neighbourhood.html", "classcomma_1_1_neighbourhood" ],
      [ "Neighbourhood_Extended", "classcomma_1_1_neighbourhood___extended.html", "classcomma_1_1_neighbourhood___extended" ],
      [ "Neighbourhood_Pure_Front", "classcomma_1_1_neighbourhood___pure___front.html", "classcomma_1_1_neighbourhood___pure___front" ],
      [ "NeighbourhoodCreator", "classcomma_1_1_neighbourhood_creator.html", "classcomma_1_1_neighbourhood_creator" ],
      [ "NeighbourhoodExtendedCreator", "classcomma_1_1_neighbourhood_extended_creator.html", "classcomma_1_1_neighbourhood_extended_creator" ],
      [ "NeighbourhoodPureFrontCreator", "classcomma_1_1_neighbourhood_pure_front_creator.html", "classcomma_1_1_neighbourhood_pure_front_creator" ],
      [ "Node", "classcomma_1_1_node.html", "classcomma_1_1_node" ],
      [ "PairFindFirstBasedFunctor", "classcomma_1_1_pair_find_first_based_functor.html", "classcomma_1_1_pair_find_first_based_functor" ],
      [ "PairSecondBasedLessFunctor", "structcomma_1_1_pair_second_based_less_functor.html", "structcomma_1_1_pair_second_based_less_functor" ],
      [ "Priority_Pair", "classcomma_1_1_priority___pair.html", "classcomma_1_1_priority___pair" ],
      [ "Queue", "classcomma_1_1_queue.html", "classcomma_1_1_queue" ],
      [ "Seeds_Pool", "classcomma_1_1_seeds___pool.html", "classcomma_1_1_seeds___pool" ],
      [ "Seeds_Pool_Boundary_Priority", "classcomma_1_1_seeds___pool___boundary___priority.html", "classcomma_1_1_seeds___pool___boundary___priority" ],
      [ "Seeds_Pool_Neighbourhood_Priority", "classcomma_1_1_seeds___pool___neighbourhood___priority.html", "classcomma_1_1_seeds___pool___neighbourhood___priority" ],
      [ "SPFullInitializator", "structcomma_1_1_s_p_full_initializator.html", "structcomma_1_1_s_p_full_initializator" ],
      [ "SPInitializator", "structcomma_1_1_s_p_initializator.html", "structcomma_1_1_s_p_initializator" ],
      [ "SPOnePointInitializator", "structcomma_1_1_s_p_one_point_initializator.html", "structcomma_1_1_s_p_one_point_initializator" ],
      [ "Subgraph", "classcomma_1_1_subgraph.html", "classcomma_1_1_subgraph" ],
      [ "Tree", "classcomma_1_1_tree.html", "classcomma_1_1_tree" ]
    ] ]
];