var annotated_dup =
[
    [ "Agglomerator", "class_agglomerator.html", "class_agglomerator" ],
    [ "Agglomerator_Anisotropic", "class_agglomerator___anisotropic.html", "class_agglomerator___anisotropic" ],
    [ "Agglomerator_Biconnected", "class_agglomerator___biconnected.html", "class_agglomerator___biconnected" ],
    [ "Agglomerator_Isotropic", "class_agglomerator___isotropic.html", "class_agglomerator___isotropic" ],
    [ "Agglomerator_Iterative", "class_agglomerator___iterative.html", "class_agglomerator___iterative" ],
    [ "Bimap", "class_bimap.html", "class_bimap" ],
    [ "Coarse_Cell", "class_coarse___cell.html", "class_coarse___cell" ],
    [ "Coarse_Cell_Container", "class_coarse___cell___container.html", "class_coarse___cell___container" ],
    [ "Coarse_Cell_Subgraph", "class_coarse___cell___subgraph.html", "class_coarse___cell___subgraph" ],
    [ "CustomPairGreaterFunctor", "struct_custom_pair_greater_functor.html", "struct_custom_pair_greater_functor" ],
    [ "CustomPairLessFunctor", "struct_custom_pair_less_functor.html", "struct_custom_pair_less_functor" ],
    [ "Dual_Graph", "class_dual___graph.html", "class_dual___graph" ],
    [ "Graph", "class_graph.html", "class_graph" ],
    [ "Neighbourhood", "class_neighbourhood.html", "class_neighbourhood" ],
    [ "Neighbourhood_Extended", "class_neighbourhood___extended.html", "class_neighbourhood___extended" ],
    [ "Neighbourhood_Pure_Front", "class_neighbourhood___pure___front.html", "class_neighbourhood___pure___front" ],
    [ "NeighbourhoodCreator", "class_neighbourhood_creator.html", "class_neighbourhood_creator" ],
    [ "NeighbourhoodExtendedCreator", "class_neighbourhood_extended_creator.html", "class_neighbourhood_extended_creator" ],
    [ "NeighbourhoodPureFrontCreator", "class_neighbourhood_pure_front_creator.html", "class_neighbourhood_pure_front_creator" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "PairFindFirstBasedFunctor", "class_pair_find_first_based_functor.html", "class_pair_find_first_based_functor" ],
    [ "PairSecondBasedLessFunctor", "struct_pair_second_based_less_functor.html", "struct_pair_second_based_less_functor" ],
    [ "Priority_Pair", "class_priority___pair.html", "class_priority___pair" ],
    [ "Queue", "class_queue.html", "class_queue" ],
    [ "Seeds_Pool", "class_seeds___pool.html", "class_seeds___pool" ],
    [ "Seeds_Pool_Boundary_Priority", "class_seeds___pool___boundary___priority.html", "class_seeds___pool___boundary___priority" ],
    [ "Seeds_Pool_Neighbourhood_Priority", "class_seeds___pool___neighbourhood___priority.html", "class_seeds___pool___neighbourhood___priority" ],
    [ "SPFullInitializator", "struct_s_p_full_initializator.html", "struct_s_p_full_initializator" ],
    [ "SPInitializator", "struct_s_p_initializator.html", "struct_s_p_initializator" ],
    [ "SPOnePointInitializator", "struct_s_p_one_point_initializator.html", "struct_s_p_one_point_initializator" ],
    [ "Subgraph", "class_subgraph.html", "class_subgraph" ],
    [ "Tree", "class_tree.html", "class_tree" ]
];