var searchData=
[
  ['agglomerate_5fone_5flevel_0',['agglomerate_one_level',['../namespacecomma.html#a2b7e1cf509b92b84db94b66033389e76',1,'comma::agglomerate_one_level(const GraphArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;graph, const AgglomerationArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;agglo, const AnisotropicArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;aniso, std::vector&lt; CoMMAIndexType &gt; &amp;fc_to_cc, std::vector&lt; CoMMAIndexType &gt; &amp;aniso_lines_indices, std::vector&lt; CoMMAIndexType &gt; &amp;aniso_lines)'],['../namespacecomma.html#a7e826673df0f42257a8ccf486ad4ef2c',1,'comma::agglomerate_one_level(const std::vector&lt; CoMMAIndexType &gt; &amp;adjMatrix_row_ptr, const std::vector&lt; CoMMAIndexType &gt; &amp;adjMatrix_col_ind, const std::vector&lt; CoMMAWeightType &gt; &amp;adjMatrix_areaValues, const std::vector&lt; CoMMAWeightType &gt; &amp;volumes, const std::vector&lt; std::vector&lt; CoMMAWeightType &gt; &gt; &amp;centers, const std::vector&lt; CoMMAWeightType &gt; &amp;priority_weights, const std::vector&lt; CoMMAIndexType &gt; &amp;anisotropicCompliantCells, const std::vector&lt; CoMMAIntType &gt; &amp;n_bnd_faces, bool build_anisotropic_lines, bool is_anisotropic, bool odd_line_length, CoMMAWeightType threshold_anisotropy, CoMMASeedsPoolT seed_ordering_type, std::vector&lt; CoMMAIndexType &gt; &amp;fc_to_cc, std::vector&lt; CoMMAIndexType &gt; &amp;agglomerationLines_Idx, std::vector&lt; CoMMAIndexType &gt; &amp;agglomerationLines, bool correction, CoMMAIntType dimension, CoMMAIntType goal_card, CoMMAIntType min_card, CoMMAIntType max_card, CoMMAIntType singular_card_thresh=1, std::optional&lt; CoMMAIndexType &gt; max_cells_in_line=std::nullopt, CoMMAIntType fc_choice_iter=1, CoMMANeighbourhoodT neighbourhood_type=CoMMANeighbourhoodT::EXTENDED)'],['../classcomma_1_1_agglomerator___isotropic.html#a7690b334b4f4d143d5edef7e015226c5',1,'comma::Agglomerator_Isotropic::agglomerate_one_level()'],['../classcomma_1_1_agglomerator___anisotropic.html#a679ba0b3f517db87b18a0707d71a6432',1,'comma::Agglomerator_Anisotropic::agglomerate_one_level()'],['../classcomma_1_1_agglomerator.html#ad318f38cc60db419207fa1def39e2269',1,'comma::Agglomerator::agglomerate_one_level()']]],
  ['agglomerationargs_1',['AgglomerationArgs',['../classcomma_1_1_agglomeration_args.html#a967adfbb31855d5e9511a9bcd1adc381',1,'comma::AgglomerationArgs::AgglomerationArgs()=default'],['../classcomma_1_1_agglomeration_args.html#a9c1a315802d5e50eeab5f6fffca0858c',1,'comma::AgglomerationArgs::AgglomerationArgs(CoMMAIntType goal_card, CoMMAIntType min_card, CoMMAIntType max_card, bool correction, CoMMASeedsPoolT seed_ordering_type, CoMMAIntType singular_card_thresh=1, CoMMAIntType fc_choice_iter=1, CoMMANeighbourhoodT neighbourhood_type=CoMMANeighbourhoodT::EXTENDED)'],['../classcomma_1_1_agglomeration_args.html',1,'comma::AgglomerationArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['agglomerator_2',['Agglomerator',['../classcomma_1_1_agglomerator.html#a4724d63a24be863a28b5eb183db3dda2',1,'comma::Agglomerator::Agglomerator()'],['../classcomma_1_1_agglomerator.html',1,'comma::Agglomerator&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['agglomerator_2eh_3',['Agglomerator.h',['../_agglomerator_8h.html',1,'']]],
  ['agglomerator_5fanisotropic_4',['Agglomerator_Anisotropic',['../classcomma_1_1_agglomerator___anisotropic.html#aeccd35ffb2739c71190c6e0545b56839',1,'comma::Agglomerator_Anisotropic::Agglomerator_Anisotropic()'],['../classcomma_1_1_agglomerator___anisotropic.html',1,'comma::Agglomerator_Anisotropic&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['agglomerator_5fbiconnected_5',['Agglomerator_Biconnected',['../classcomma_1_1_agglomerator___biconnected.html#a0744384ce714c0f8dba59eca630dbdd1',1,'comma::Agglomerator_Biconnected::Agglomerator_Biconnected()'],['../classcomma_1_1_agglomerator___biconnected.html',1,'comma::Agglomerator_Biconnected&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['agglomerator_5fisotropic_6',['Agglomerator_Isotropic',['../classcomma_1_1_agglomerator___isotropic.html#a6d589efa4a8648631a2b946763b04dd6',1,'comma::Agglomerator_Isotropic::Agglomerator_Isotropic()'],['../classcomma_1_1_agglomerator___isotropic.html',1,'comma::Agglomerator_Isotropic&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['agglomerator_5fiterative_7',['Agglomerator_Iterative',['../classcomma_1_1_agglomerator___iterative.html#ad1c5165595a1eb8374362564b0cf5b1a',1,'comma::Agglomerator_Iterative::Agglomerator_Iterative()'],['../classcomma_1_1_agglomerator___iterative.html',1,'comma::Agglomerator_Iterative&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['anisotropicargs_8',['AnisotropicArgs',['../classcomma_1_1_anisotropic_args.html#a3848b9ba1ca67de43f2bcf811dc73bf0',1,'comma::AnisotropicArgs::AnisotropicArgs()'],['../classcomma_1_1_anisotropic_args.html',1,'comma::AnisotropicArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt;']]],
  ['anisotropiccompliantcells_9',['anisotropicCompliantCells',['../classcomma_1_1_anisotropic_args.html#afcec684865d7bae8b341fd5c415c2d43',1,'comma::AnisotropicArgs']]],
  ['anisotropicline_10',['AnisotropicLine',['../classcomma_1_1_agglomerator___anisotropic.html#a9479673f4208b7edd7c0b8884a06c4b7',1,'comma::Agglomerator_Anisotropic']]],
  ['anisotropiclineptr_11',['AnisotropicLinePtr',['../classcomma_1_1_agglomerator___anisotropic.html#a9de6a86962a319a3cd058000fade94e0',1,'comma::Agglomerator_Anisotropic']]],
  ['args_2eh_12',['Args.h',['../_args_8h.html',1,'']]]
];
