var searchData=
[
  ['agglomerate_5fone_5flevel_0',['agglomerate_one_level',['../classcomma_1_1_agglomerator___anisotropic.html#a679ba0b3f517db87b18a0707d71a6432',1,'comma::Agglomerator_Anisotropic::agglomerate_one_level()'],['../namespacecomma.html#a2b7e1cf509b92b84db94b66033389e76',1,'comma::agglomerate_one_level(const GraphArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;graph, const AgglomerationArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;agglo, const AnisotropicArgs&lt; CoMMAIndexType, CoMMAWeightType, CoMMAIntType &gt; &amp;aniso, std::vector&lt; CoMMAIndexType &gt; &amp;fc_to_cc, std::vector&lt; CoMMAIndexType &gt; &amp;aniso_lines_indices, std::vector&lt; CoMMAIndexType &gt; &amp;aniso_lines)'],['../namespacecomma.html#a263242d07618a6aaded21e7fada33004',1,'comma::agglomerate_one_level(const std::vector&lt; CoMMAIndexType &gt; &amp;adjMatrix_row_ptr, const std::vector&lt; CoMMAIndexType &gt; &amp;adjMatrix_col_ind, const std::vector&lt; CoMMAWeightType &gt; &amp;adjMatrix_areaValues, const std::vector&lt; CoMMAWeightType &gt; &amp;volumes, const std::vector&lt; std::vector&lt; CoMMAWeightType &gt; &gt; &amp;centers, const std::vector&lt; CoMMAWeightType &gt; &amp;priority_weights, const std::vector&lt; CoMMAIndexType &gt; &amp;anisotropicCompliantCells, const std::vector&lt; CoMMAIntType &gt; &amp;n_bnd_faces, bool build_anisotropic_lines, bool is_anisotropic, bool odd_line_length, CoMMAWeightType threshold_anisotropy, CoMMASeedsPoolT seed_ordering_type, std::vector&lt; CoMMAIndexType &gt; &amp;fc_to_cc, std::vector&lt; CoMMAIndexType &gt; &amp;agglomerationLines_Idx, std::vector&lt; CoMMAIndexType &gt; &amp;agglomerationLines, bool correction, CoMMAIntType dimension, CoMMAIntType goal_card, CoMMAIntType min_card, CoMMAIntType max_card, CoMMAAspectRatioT aspect_ratio=CoMMAAspectRatioT::DIAMETER_OVER_RADIUS, CoMMAIntType singular_card_thresh=1, std::optional&lt; CoMMAIndexType &gt; max_cells_in_line=std::nullopt, CoMMAIntType fc_choice_iter=1, CoMMANeighbourhoodT neighbourhood_type=CoMMANeighbourhoodT::EXTENDED)'],['../classcomma_1_1_agglomerator.html#ad318f38cc60db419207fa1def39e2269',1,'comma::Agglomerator::agglomerate_one_level()'],['../classcomma_1_1_agglomerator___isotropic.html#a7690b334b4f4d143d5edef7e015226c5',1,'comma::Agglomerator_Isotropic::agglomerate_one_level()']]],
  ['agglomerationargs_1',['AgglomerationArgs',['../classcomma_1_1_agglomeration_args.html#a8c72fefd5efa075dd83007b40abb0414',1,'comma::AgglomerationArgs::AgglomerationArgs(CoMMAIntType goal_card, CoMMAIntType min_card, CoMMAIntType max_card, bool correction, CoMMASeedsPoolT seed_ordering_type, CoMMAAspectRatioT aspect_ratio=CoMMAAspectRatioT::DIAMETER_OVER_RADIUS, CoMMAIntType singular_card_thresh=1, CoMMAIntType fc_choice_iter=1, CoMMANeighbourhoodT neighbourhood_type=CoMMANeighbourhoodT::EXTENDED)'],['../classcomma_1_1_agglomeration_args.html#a967adfbb31855d5e9511a9bcd1adc381',1,'comma::AgglomerationArgs::AgglomerationArgs()=default']]],
  ['agglomerator_2',['Agglomerator',['../classcomma_1_1_agglomerator.html#a4724d63a24be863a28b5eb183db3dda2',1,'comma::Agglomerator']]],
  ['agglomerator_5fanisotropic_3',['Agglomerator_Anisotropic',['../classcomma_1_1_agglomerator___anisotropic.html#aeccd35ffb2739c71190c6e0545b56839',1,'comma::Agglomerator_Anisotropic']]],
  ['agglomerator_5fbiconnected_4',['Agglomerator_Biconnected',['../classcomma_1_1_agglomerator___biconnected.html#afa1a29652d16d3ef403271c90e3bae3b',1,'comma::Agglomerator_Biconnected']]],
  ['agglomerator_5fisotropic_5',['Agglomerator_Isotropic',['../classcomma_1_1_agglomerator___isotropic.html#a745a11f75eb2f77d692f1e81ad40e26f',1,'comma::Agglomerator_Isotropic']]],
  ['agglomerator_5fiterative_6',['Agglomerator_Iterative',['../classcomma_1_1_agglomerator___iterative.html#a0b0e8ca4f3be3d853fa5179f95065d0e',1,'comma::Agglomerator_Iterative']]],
  ['anisotropicargs_7',['AnisotropicArgs',['../classcomma_1_1_anisotropic_args.html#a3848b9ba1ca67de43f2bcf811dc73bf0',1,'comma::AnisotropicArgs']]],
  ['arcomputer_8',['ARComputer',['../classcomma_1_1_a_r_computer.html#afd5992fc6b2a72a698e329231232ce1f',1,'comma::ARComputer']]],
  ['ardiameter_9',['ARDiameter',['../classcomma_1_1_a_r_diameter.html#af33b79330d0b514b7bb8dfc71e8047ca',1,'comma::ARDiameter']]],
  ['ardiamoverminedge_10',['ARDiamOverMinEdge',['../classcomma_1_1_a_r_diam_over_min_edge.html#ac07384fcb7ebc857ad93687acb5fdf23',1,'comma::ARDiamOverMinEdge']]],
  ['ardiamoverradius_11',['ARDiamOverRadius',['../classcomma_1_1_a_r_diam_over_radius.html#a5f784d4af3b7cb4f3454cfff262f52ef',1,'comma::ARDiamOverRadius']]],
  ['arexternalweightoverradius_12',['ARExternalWeightOverRadius',['../classcomma_1_1_a_r_external_weight_over_radius.html#ae48d84bb3267022be949f2b2ccd9f2f1',1,'comma::ARExternalWeightOverRadius']]],
  ['arexternalweights_13',['ARExternalWeights',['../classcomma_1_1_a_r_external_weights.html#a904b8f12f9023d62d449144db440b156',1,'comma::ARExternalWeights']]],
  ['armaxbarydistanceoverradius_14',['ARMaxBaryDistanceOverRadius',['../classcomma_1_1_a_r_max_bary_distance_over_radius.html#a0d5be70a33a76d4906afcf689de45f51',1,'comma::ARMaxBaryDistanceOverRadius']]],
  ['armaxoverminbarydistance_15',['ARMaxOverMinBaryDistance',['../classcomma_1_1_a_r_max_over_min_bary_distance.html#a418503929bb754b7fe5b786f7b08d2bf',1,'comma::ARMaxOverMinBaryDistance']]],
  ['aroverinternalweights_16',['AROverInternalWeights',['../classcomma_1_1_a_r_over_internal_weights.html#ae257c712a3ba0f4387f96a44ef2c9cb0',1,'comma::AROverInternalWeights']]],
  ['arovermeasure_17',['AROverMeasure',['../classcomma_1_1_a_r_over_measure.html#a04a88c9f0ebcdacf29281113415e4f8d',1,'comma::AROverMeasure']]]
];
